/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        //TestCases tests = new TestCases(); // Initialize your test class
        //Search_Amazon search = new Search_Amazon();
        //Count_Hyperlinks hyperlinks = new Count_Hyperlinks();
        Automate_post_onLinkedin linkedin = new Automate_post_onLinkedin();
        // Automate_image_urls images = new Automate_image_urls();
        //Automate_nested_frames_text frames = new Automate_nested_frames_text();
        //Automate_imdb_ratings imdb = new Automate_imdb_ratings();
        //Automate_window_handle window = new Automate_window_handle();

        //TODO: call your test case functions one after other here

        //tests.testCase01();
        //search.AmazonSearch();
        //hyperlinks.hyperlinksCount();
        linkedin.linkedinPost();
        // images.imageUrl();
        //frames.nestedFrames();
        //imdb.imdbRatings();
        //window.windowHandle();

        //END Tests


        //tests.endTest(); // End your test by clearning connections and closing browser
        //search.endTest();
        //hyperlinks.endTest();
        linkedin.endTest();
        // images.endTest();
        //frames.endTest();
        //imdb.endTest();
        //window.endTest();
        
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
